resources:
  repositories:
    - repository: self
      trigger: none

variables:
  runRestoreAndBuild: false  # Default to true, can be overridden

stages:
- stage: Build
  displayName: Build .Net Core Solution
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - ${{ if eq(variables['runRestoreAndBuild'], 'true') }}:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: 'restore'
          projects: '**/*.sln'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          projects: '**/*.sln'
    
    - script: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
      displayName: 'Install ReportGenerator'
    
    - task: DotNetCoreCLI@2
      displayName: Run Unit Tests and Collect Coverage
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--configuration $(BuildConfiguration) --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Agent.TempDirectory)/**/coverage.cobertura.xml' 
    
    - script: |
        ls $(Agent.TempDirectory)
      displayName: 'Debug Agent.TempDirectory'
    
    - script: |
        ls $(Build.SourcesDirectory)
      displayName: 'Build.SourcesDirectory'
    
    
