resources:
  repositories:
    - repository: self
      trigger: none

variables:
  runRestoreAndBuild: true  # Default to true, can be overridden

stages:
- stage: Build
  displayName: Build .Net Core Solution
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - ${{ if eq(variables['runRestoreAndBuild'], 'true') }}:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: 'restore'
          projects: '**/*.sln'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          projects: '**/*.sln'
    
    - script: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
      displayName: 'Install ReportGenerator'
    
    - script: dotnet test $(Build.SourcesDirectory)/tests/UnitTests/Calculator.UnitTests/CalculatorAPIUnitTests/CalculatorAPIUnitTests.csproj --collect:"XPlat Code Coverage"
      displayName: 'Run Unit Tests and Collect Coverage'
    
    - script: |
        COVERAGE_FILE_PATH=$(find $(Build.SourcesDirectory)/tests/UnitTests/Calculator.UnitTests/CalculatorAPIUnitTests/TestResults -name 'coverage.cobertura.xml' | head -n 1)
        COVERAGE_FILE_PATH=$(dirname "$COVERAGE_FILE_PATH")
        echo "##vso[task.setvariable variable=CoverageDirectory]$COVERAGE_FILE_PATH"
        echo "Coverage directory set to: $COVERAGE_FILE_PATH"
      displayName: 'Find GUID Directory'

    - script: |
        reportgenerator "-reports:$(CoverageDirectory)/coverage.cobertura.xml" "-targetdir:$(CoverageDirectory)/CoverageReport" "-reporttypes:Html"
      displayName: 'Generate HTML report'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish Code Coverage Results'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(CoverageDirectory)/coverage.cobertura.xml'
        reportDirectory: '$(CoverageDirectory)/CoverageReport'
        failIfCoverageEmpty: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Code Coverage Report'
      inputs:
        PathtoPublish: '$(CoverageDirectory)/CoverageReport'
        ArtifactName: 'CodeCoverage'
        publishLocation: 'Container'
    
