resources:
  repositories:
    - repository: self
      trigger: none

stages:
- stage: Build
  displayName: Build .Net Core Solution
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.sln'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.sln'
    
    - script: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
      displayName: 'Install ReportGenerator'
    
    - task: DotNetCoreCLI@2
      displayName: Run Unit Tests and Collect Coverage
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--configuration $(BuildConfiguration) --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/coverage.cobertura.xml' 
    
    - script: |
        ls $(Build.SourcesDirectory)/TestResults/Coverage/
      displayName: 'Debug'
    
    - script: |
        reportgenerator "-reports:$(Build.SourcesDirectory)/TestResults/Coverage/coverage.cobertura.xml" "-targetdir:$(Build.SourcesDirectory)/TestResults/Coverage/Reports" "-reporttypes:Html"
      displayName: 'Generate code coverage report'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage results'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Build.SourcesDirectory)/TestResults/Coverage/coverage.cobertura.xml'
        reportDirectory: '$(Build.SourcesDirectory)/TestResults/Coverage/Reports'
        failIfCoverageEmpty: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish code coverage report'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/TestResults/Coverage/Reports'
        ArtifactName: 'CodeCoverage'
        publishLocation: 'Container'
